services:
  postgres:
    image: postgres:16-alpine
    container_name: db_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: budget-service
      POSTGRES_USER: budgetadmin
      POSTGRES_PASSWORD: budgetadmin++
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "9432:5432"
    networks:
      - app_network
  redis:
    image: redis:7-alpine
    container_name: rd_portgres
    restart: unless-stopped
    command: redis-server --requirepass pr01ec1s413
    ports:
      - "6379:6379"
    networks:
      - app_network
volumes:
  postgres_data:
networks:
  app_network:
    driver: bridge

# docker compose up -d